### ISSUE TITLE
需求：建议添加标签来提高信息价值

### ISSUE THREAD

**Issue by QIN2DIM** [CollegesChat/university-information#115]
1. 建议标注**回答时间**

   显然，一些「问答」会随着时间推移逐渐过时，

   - 例如“宿舍是否有空调”可能随着时间的推移，学校就给装上了；
   - “取外卖的地方离宿舍楼多远”可能之前一直都能进校送到楼下，疫情期间外卖都进不来学校，或者疫情过去了又能“恢复如初”；
   - “校园网怎么样”也许今天还是埋地瓜的网速，过几个学期就"500M家宽"或“光纤入户”；  

2. 建议标注回答者的**所在校区**

   这是个显而易见的问题，不同校区的生活学习条件差异巨大。

**Comment by Netrvin** [comment]
1. 问卷完成时间我们会考虑在新版加上，目前展示的数据均在去年较短时间内收集，故当时不考虑对回答时间做详细标注
2. 校区我们已经有在区分，部份问卷数据的学校名称后有加上校区
