### ISSUE TITLE
建议添加：学校对应的教育邮箱申请是否方便

### ISSUE THREAD

**Issue by SherkeyXD** [CollegesChat/university-information#120]
edu邮箱可以用来嫖好多资源的

**Comment by Crazyokd** [comment]
赞同

**Comment by Cyenoch** [comment]
赞

**Comment by zweie** [comment]
对啊，而且有的学校甚至不让申请教育邮箱，这一点就亏很多了，也体现出学校的给学生资源的多少

**Comment by aisuneko** [comment]
这个应该不算生活质量问题？

**Comment by SherkeyXD** [comment]
> 这个应该不算生活质量问题？

确实不太好界定，因为不同人群需求不同
比如计算机系学生可能会关心，外语系的学生就不太需要...
征求一下大家的意见？

**Comment by Crazyokd** [comment]
甚至还有一种情况，学校的教育邮箱不被认可。

**Comment by aisuneko** [comment]
@SherkeyXD 个人认为这个属于办学方面的问题，我们主要调查的是生活条件（宿舍，食堂，...）和某些规章制度，可以去看看我们的问卷
