### ISSUE TITLE
建议添加知网与四六级情况

### ISSUE THREAD

**Issue by 8616497** [CollegesChat/university-information#123]
希望知道知网的免费与否和四六级报考时间。

**Comment by wuhang2003** [comment]
> 希望知道知网的免费与否和四六级报考时间。

~~就谈知网格局小了~~
我觉得这个问题可以拓展到学校买了哪些数据库，~~数据库可以使用哪些资源~~（问题太长了还是聊到数据库吧）
四六级和计算机等社会性考试的报名时间可能每年都会有变动，参考意义不是很大

**Comment by aisuneko** [comment]
与 #139 重复
