### ISSUE TITLE
建议添加第二课堂学分情况

### ISSUE THREAD

**Issue by jesee030** [CollegesChat/university-information#125]
我校各种骚操作，叫学生去拔草听讲座的，加分不透明，系统建3年没好QAQ

**Comment by jihuaTEL** [comment]
很难不支持

**Comment by aisuneko** [comment]
参见 #131 #123

**Comment by jesee030** [comment]
虽说解释权在校方，但是学长学姐打一声招呼就好让学弟学妹有规划去进行学习安排，而不是去做辅导员KPI，对大学影响挺大的，考研找工作可能会耽误在这上面
