### ISSUE TITLE
重复项目可以合并

### ISSUE THREAD

**Issue by zyk2507** [CollegesChat/university-information#127]
![image](https://user-images.githubusercontent.com/93830642/175560778-e7425489-96e3-4485-afd9-3890e6ba5d48.png)
画花括号的感觉有点乱，希望可以稍微处理一下。

**Comment by aisuneko** [comment]
我们正在开发新版问卷，会通过直接从列表中选择校（区）而不是自行输入校（区）名的方式解决。
