### ISSUE TITLE
建议添加转专业容易与否

### ISSUE THREAD

**Issue by SherkeyXD** [CollegesChat/university-information#129]
虽然学校招生网站上能查到，但是免不了有说大话的情况

**Comment by zweie** [comment]
转专业默认都是难的吧，你人跑了一个两个，那学院的钱就少了些，谁愿意到手的肉跑了，肯定都是设置难的

**Comment by SherkeyXD** [comment]
> 转专业默认都是难的吧，你人跑了一个两个，那学院的钱就少了些，谁愿意到手的肉跑了，肯定都是设置难的

似乎有些学校大一有统一安排，这些大学应该会容易一些

**Comment by eliaszon** [comment]
需要加的。招生网站上能查到，但是会有变动。

**Comment by aisuneko** [comment]
本项目主要关心与大学**生活质量**有关的信息而不是学业相关信息；参见 #131 #125
