### ISSUE TITLE
可否考虑增加填写学校是否有独特的招生政策？

### ISSUE THREAD

**Issue by zweie** [CollegesChat/university-information#131]
有的学校有独特的招生政策，而难对外界所知

**Comment by aisuneko** [comment]
这个项目主要是侧重调查大学生活质量，招生政策似乎跟其关系不大

**Comment by zweie** [comment]
> 这个项目主要是侧重调查大学生活质量，招生政策似乎跟其关系不大

唔，不好意思，是我有些误解了。
