### ISSUE TITLE
[protected email] 现在可见

### ISSUE THREAD

**Issue by HairlessVillager** [CollegesChat/university-information#134]
现在可以在问卷结果的页面上看见填写问卷者的[protected email]，不需要刷新。

**Comment by aisuneko** [comment]
是在网站上还是在 generated 分支里的生成的MD文档里？

**Comment by aisuneko** [comment]
我这边（在网站上）没有复现；可以提供截图一类的吗？

**Comment by HairlessVillager** [comment]
你好，抱歉现在才看到这个 issue 还开着，现在已经不能复现这个问题了🥰thx
