### ISSUE TITLE
希望删除或合并 江苏条目下“中国矿业大学徐州”

### ISSUE THREAD

**Issue by LymoneLM** [CollegesChat/university-information#149]
此条目系学长误操作，CUMT全名就是中国矿业大学，并没有“中国矿业大学徐州”的名字
唯一的提交者ID为A15280
希望删除此条目或者合并内容到“中国矿业大学”条目
不胜感激
您的项目对我们的帮助真的非常大！

**Comment by Rachel030219** [comment]
多谢指正！稍后问卷数据更新时，我们将把 A15280 合并至中国矿业大学条目内。

**Comment by Rachel030219** [comment]
已经将 A15280 合并至中国矿业大学条目，等待缓存刷新即可
