### ISSUE TITLE
建议归档指定日期前的问卷数据

### ISSUE THREAD

**Issue by Rachel030219** [CollegesChat/university-information#155]
考虑到项目上线已有数年，期间还经历了一轮新冠防控政策的变迁等等，目前很多学校的政策、建设水平等已与早期大不相同，将早期数据归档想必对于数据查询与甄别来说很有帮助。

我目前的设想是，在 `mkdocs` 生成的网页将存档数据放在「已归档数据」的同级目录中，而生成的文件则放在 `docs` 目录的 `archived` 文件夹下。这样不仅可以方便地查找旧数据，还保证了部分有一定价值的资料免于流失。

不知这一设想的合理性如何，以及如果这一归档形式不够好的话，如何改进比较好？

**Comment by NCBM** [comment]
个人希望能对现有数据在页面上标明数据的大致提交时间（如 `YYYY-MM`）

**Comment by Rachel030219** [comment]
closed by #157
