### ISSUE TITLE
希望删除“下北泽野兽大学”条目

### ISSUE THREAD

**Issue by 30266-Official** [CollegesChat/university-information#158]
玩梗yamero

**Comment by Rachel030219** [comment]
个人来说其实我是并不介意存在部分玩梗条目的，毕竟从各种意义上，这些大学存在的可能性都很低，并不会对查询信息造成困扰，反而可以博读者一乐，何乐而不为呢？

或者说，有什么必须移除的原因吗？若您详细描述问题，我们就可以进行进一步的探讨，确定是否应该保留该条目。

**Comment by aisuneko** [comment]
> 个人来说其实我是并不介意存在部分玩梗条目的，毕竟从各种意义上，这些大学存在的可能性都很低，并不会对查询信息造成困扰，反而可以博读者一乐，何乐而不为呢？
> 
> 或者说，有什么必须移除的原因吗？若您详细描述问题，我们就可以进行进一步的探讨，确定是否应该保留该条目。

确实可以像wiki那样加入一个幽默页面template作为彩蛋（

**Comment by 30266-Official** [comment]
> 个人来说其实我是并不介意存在部分玩梗条目的，毕竟从各种意义上，这些大学存在的可能性都很低，并不会对查询信息造成困扰，反而可以博读者一乐，何乐而不为呢？
> 
> 或者说，有什么必须移除的原因吗？若您详细描述问题，我们就可以进行进一步的探讨，确定是否应该保留该条目。

取决于你们对这个仓库的定位。如果你们认为这个项目是严肃的，那么这种玩梗类条目显然是不合适的。如果你们认为这个项目不是严肃的，那么我希望你们可以容忍更多的玩梗条目，比如原神大学 嘉然厨艺学院 之类的乱七八糟的东西

**Comment by Rachel030219** [comment]
> 不熟悉互联网文化梗的人会质疑这个仓库的信息真实性。

这确实有道理，但考虑到大部分学校都已经被列在对应地区中，我相当怀疑有多少不熟悉互联网文化梗的人会一路找到「其他」下面的玩梗条目，然后因为数万条数据里有一条玩梗而觉得仓库信息不真实。

> 取决于你们对这个仓库的定位。如果你们认为这个项目是严肃的，那么这种玩梗类条目显然是不合适的。如果你们认为这个项目不是严肃的，那么我希望你们可以容忍更多的玩梗条目，比如原神大学 嘉然厨艺学院 之类的乱七八糟的东西

我们从来没有不容忍过更多的玩梗条目，只是还没有人写而已，显然很多时候「严肃」和「不严肃」完全可以并存。我们只是一个用爱发电的、自发维护的平台，维护者也都是非常普通的学生罢了，提交问卷的人愿意幽默，我们何苦惺惺作态？难道一个游戏的剧情里全是梗，大家就会因此忘记剧情给大家带来的那些感动与不舍吗？

**Comment by 30266-Official** [comment]
> 我们从来没有不容忍过更多的玩梗条目，只是还没有人写而已，显然很多时候「严肃」和「不严肃」完全可以并存。我们只是一个用爱发电的、自发维护的平台，维护者也都是非常普通的学生罢了，提交问卷的人愿意幽默，我们何苦惺惺作态？难道一个游戏的剧情里全是梗，大家就会因此忘记剧情给大家带来的那些感动与不舍吗？

我想要指出的是，这里的玩梗和游戏剧情中的梗有本质不同。但是我感觉再说下去没用了，不再解释了。It's all up to you
