### ISSUE TITLE
已归档数据不准确

### ISSUE THREAD

**Issue by C315703603** [CollegesChat/university-information#159]
统计的时间在22年6-7月，如今疫情已过，有很多新的标准，希望能重新开启统计

**Comment by Him392** [comment]
确实，不过也不至于把之前的全部数据都一棒子打死

**Comment by Rachel030219** [comment]
「已归档数据」的存在主要是为了「归档」疫情时代提交的数据，或者说「已归档数据」本身就是过时数据。如果有部分学校只有已归档数据，就只能是因为在这所学校就读的朋友们还没有提交了，也许可以试着联系一下？
