### ISSUE TITLE
这网站加载太慢了

### ISSUE THREAD

**Issue by Aloys233** [CollegesChat/university-information#160]
四川移动网络
cn.colleges.chat是香港服务器，却有1S+的延迟
![image](https://github.com/CollegesChat/university-information/assets/79312288/8e4e255f-1151-4e30-ad04-b31bcfe182db)
静态文件加载也慢

**Comment by Aloys233** [comment]
而且最终是加载不出来

**Comment by EricZhou05** [comment]
+1

**Comment by Netrvin** [comment]
目前已暂停重定向到 cn.colleges.chat ，可先尝试访问托管于 Cloudflare Pages 的 https://colleges.chat

**Comment by Aloys233** [comment]
好的👌
