### ISSUE TITLE
项目中，“深圳职业技术学院”的新名称未修改完全

### ISSUE THREAD

**Issue by bsdayo** [CollegesChat/university-information#207]
约 1 年前我发了 https://github.com/CollegesChat/university-information/discussions/182 这个 Discussion，反映“深圳职业技术学院”更名为“深圳职业技术大学”一事；刚刚看了一下发现其实并没有修改完全。

这导致 https://colleges.chat 侧边栏里的“深圳职业技术大学”并没有正常归在广东省内，而是在“其他”里。印象里修改前是没有这个问题的。

也许需要修改一下这里？

https://github.com/CollegesChat/university-information/blob/a6c447164aa7422c516fc4af1fb7da4f3c5c2cd9/questionnaires/colleges.csv#L1908

**Comment by Rachel030219** [comment]
已在 commit e355d6f 中解决，数据更新需要时间，请耐心等候，感谢帮助定位问题！
